config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get "facilities/index"
  devise_for :users
  
  resources :hotels do
    resources :rooms, only: [:index, :show]
    resources :opinions, only: [:index, :create]
  end

  resources :users do
    resources :reservations, only: [:index, :show]
  end

  resources :payments, only: [:create, :update]
  resources :opinions, only: [:index, :show, :destroy]

  # Ruta raíz
authenticated :user do
  root to: 'hotels#index', as: :authenticated_root
end
get "admin/dashboard", to: 'admin#index', as: :admin_dashboard_index

devise_scope :user do
unauthenticated do
  root to: 'devise/sessions#new', as: :unauthenticated_root
end
end

devise_for :users, skip: [:sessions]
as :user do
  delete 'users/sign_out' => 'devise/sessions#destroy'
end





#get "admin/hotel_management", to: 'admin#hotel_management', as: :admin_hotel_management
get "admin/room_management", to: 'admin#room_management', as: :admin_room_management
get "admin/hotels", to: 'hotel_management#index', as: :admin_hotels



  # Health check y PWA routes
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get 'facilities', to: 'facilities#index', as: 'facilities'
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :reservation
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy!

    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:reservation_id, :method, :status)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :reservation_id, style: "display: block" %>
    <%= form.text_field :reservation_id %>
  </div>

  <div>
    <%= form.label :method, style: "display: block" %>
    <%= form.text_field :method %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Reservation:</strong>
    <%= payment.reservation_id %>
  </p>

  <p>
    <strong>Method:</strong>
    <%= payment.method %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= payment.status %>
  </p>

</div>

app/views/payments/edit.html.erb
<% content_for :title, "Editing payment" %>

<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Payments" %>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<% content_for :title, "New payment" %>

<h1>New payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>