config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get "facilities/index"
  devise_for :users
  
  resources :hotels do
    resources :rooms, only: [:index, :show]
    resources :opinions, only: [:index, :create]
  end

  resources :users do
    resources :reservations, only: [:index, :show]
  end

  resources :payments, only: [:create, :update]
  resources :opinions, only: [:index, :show, :destroy]

  # Ruta raíz
authenticated :user do
  root to: 'hotels#index', as: :authenticated_root
end
get "admin/dashboard", to: 'admin#index', as: :admin_dashboard_index

devise_scope :user do
unauthenticated do
  root to: 'devise/sessions#new', as: :unauthenticated_root
end
end

devise_for :users, skip: [:sessions]
as :user do
  delete 'users/sign_out' => 'devise/sessions#destroy'
end





#get "admin/hotel_management", to: 'admin#hotel_management', as: :admin_hotel_management
get "admin/room_management", to: 'admin#room_management', as: :admin_room_management
get "admin/hotels", to: 'hotel_management#index', as: :admin_hotels



  # Health check y PWA routes
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get 'facilities', to: 'facilities#index', as: 'facilities'
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :opinions, dependent: :destroy
  has_many :reviews
  has_one_attached :image

  def average_rating
    reviews.average(:rating) || 0
  end
  def average_rating
    opinions.average(:rating).to_f.round(2)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all

    if params[:room_type].present? || params[:price_min].present? || params[:price_max].present? ||
       params[:beds].present? || params[:available_from].present? || params[:available_to].present? || params[:guests].present?
      
      @hotels = @hotels.joins(:rooms).where(rooms: room_search_params).distinct
    end
  end

  


  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy!

    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :address, :description)
    end

    def room_search_params
      conditions = {}

      # Filtrar por tipo de habitación
      conditions[:room_type] = params[:room_type] if params[:room_type].present?

      # Filtrar por rango de precios
      if params[:price_min].present? && params[:price_max].present?
        conditions[:price] = params[:price_min]..params[:price_max]
      elsif params[:price_min].present?
        conditions[:price] = params[:price_min]..Float::INFINITY
      elsif params[:price_max].present?
        conditions[:price] = 0..params[:price_max]
      end

      # Filtrar por cantidad de camas
      conditions[:beds] = params[:beds] if params[:beds].present?

      # Filtrar por disponibilidad
      if params[:available_from].present? && params[:available_to].present?
        conditions[:available_from] = params[:available_from]
        conditions[:available_to] = params[:available_to]
      end

      # Filtrar por número de personas
      conditions[:guests] = params[:guests] if params[:guests].present?

      conditions
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel) do |form| %>
  <% if hotel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>">
  <p>
    <strong>Name:</strong>
    <%= hotel.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= hotel.address %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= hotel.description %>
  </p>

</div>

app/views/hotels/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
  <div class="container-fluid">
    <%= link_to "Hotels", "/", class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0"> <!-- Added ms-auto here -->
        <% if user_signed_in? %>
          <% if !controller.action_name.in?(%w[new create]) %>
            <li class="nav-item">
              <%= link_to "Reservations", user_reservations_path(current_user), class: "nav-link" %>
            </li>
          <% end %>
          <% if current_user.role == "admin" %>
            <li class="nav-item">
              <%= link_to "Admin Panel", admin_dashboard_index_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Logout", users_sign_out_path, turbo_method: :delete, class: "nav-link btn btn-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-outline-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/hotels/edit.html.erb
<% content_for :title, "Editing hotel" %>

<h1>Editing hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Show this hotel", @hotel %> |
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/index.html.erb
<% render partial: "hotels/menu"%>

<%= render "menu", hide_menu_option: @hide_menu_option %>

<div class="container mt-4">
  <h2 class="text-center">Búsqueda de Hoteles</h2>
  
  <div class="container">
    <div class="row">
      <!-- Columna de búsqueda -->
      <div class="col-lg-4 col-md-6 mb-3">
        <div class="card">
          <div class="card-header">
            <h5 class="card-title">Filtrar y Buscar</h5>
          </div>
          <div class="card-body">
            <%= form_with url: hotels_path, method: :get, local: true, class: "form-inline" do |form| %>
              <div class="form-group mb-3 w-100">
                <%= form.label :room_type, "Tipo de Habitación", class: "form-label" %>
                <%= form.select :room_type, options_for_select(["Single", "Double", "Suite"], params[:room_type]), { prompt: "Seleccionar Tipo" }, class: "form-control w-100" %>
              </div>

              <div class="form-group mb-3 w-100">
                <%= form.label :price_range, "Rango de Precio", class: "form-label" %>
                <div class="d-flex align-items-center w-100">
                  <%= form.text_field :price_min, placeholder: "Min", class: "form-control w-50 mr-2" %>
                  <span>-</span>
                  <%= form.text_field :price_max, placeholder: "Max", class: "form-control w-50 ml-2" %>
                </div>
              </div>

              

              <div class="form-group mb-3 w-100">
                <%= form.label :number_of_guests, "Número de Huéspedes", class: "form-label" %>
                <%= form.number_field :number_of_guests, placeholder: "Cantidad", class: "form-control w-100" %>
              </div>

              <%= form.submit "Buscar", class: "btn btn-primary btn-block" %>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Columna de hoteles -->
      <div class="col-lg-8 col-md-6">
        <div class="row">
          <% @hotels.each do |hotel| %>
            <div class="col-lg-6 col-md-12 mb-4">
              <div class="card h-100">
                <% if hotel.image.attached? %>
                  <%= image_tag hotel.image, class: "card-img-top", alt: "Hotel Image" %>
                <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= hotel.name %></h5>
                  <p class="card-text"><%= hotel.description %></p>
                  <p class="card-text"><strong>Calificación Promedio:</strong> <%= hotel.average_rating %></p>
                  <%= link_to "Reservar Habitación", hotel_rooms_path(hotel), class: "btn btn-primary btn-block" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hotels/new.html.erb
<%= form_with(model: @hotel, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :average_rating %>
    <%= form.number_field :average_rating, step: 0.1, class: "form-control" %>
  </div>

  <%= form.submit "Create Hotel", class: "btn btn-primary" %>
<% end %>

app/views/hotels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hotel %>

<div>
  <%= link_to "Edit this hotel", edit_hotel_path(@hotel) %> |
  <%= link_to "Back to hotels", hotels_path %>

  <%= button_to "Destroy this hotel", @hotel, method: :delete %>
</div>